### Import Libraries

In [165]:
import cv2
import numpy as np
import random
import math

### Define `show()` to control termination of image window

In [2]:
def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

### Read in the image. If width is greater than 800 pixels, reduce size.

In [54]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
height = int(image_file.shape[0] * scale_factor/100)
width = int(image_file.shape[1] * scale_factor/100)
dimensions = (width,height)

clear_image = cv2.resize(image_file, dimensions)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:100


### Display image

In [4]:
cv2.imshow("Resized Image",clear_image)

show()

### Display shape information of image (number of rows, number of columns and number of channels)

In [5]:
clear_image.shape

(866, 1300, 3)

### Two ways of displaying value of a pixel of particular channel

In [6]:
clear_image[200,200,2], clear_image.item((200,200,2))

(19, 19)

### Make copy of image to play around with.

In [7]:
ci = clear_image.copy()
cv2.imshow("ci", ci)
show()

### Two ways of setting the value of a pixel of a particular channel

In [8]:
ci = clear_image.copy()
ci[0,0] = (0,0,4)
ci[0,0,2], clear_image[0,0,2]

(4, 136)

In [9]:
ci.itemset((0,0,2), 42)
ci[0,0,2], clear_image[0,0,2]

(42, 136)

### Display a slice of the image

In [10]:
ci = clear_image.copy()
cv2.imshow("ci",ci[100:,100:,0])
show()

### Create data with NumPy and display

In [11]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.rand(height,width,channels)
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

In [12]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.randn(height,width,channels)
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

### Not quite getting it with randints

In [13]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

start = 1
stop = 201
number = 200
channels = 3

try:
    contrived_image = np.random.randint(start,stop,(number,number))
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

Entered faulty number of channels


In [14]:
contrived_image.shape

(200, 200)

In [15]:
clear_image[0,0]

array([109, 122, 136], dtype=uint8)

## Modifying Images
### First, change value of colours deterministically

In [16]:
ci = clear_image.copy()
for r in range(ci.shape[0]):
    for c in range(ci.shape[1]):
#         if r > 128:
#             val = ci[r,c,0]
#         else:
        val1 = ci[r,c,2]
        val2 = ci[r,c,0]
        val3 = ci[r,c,1]
        ci[r,c] = (val3,val3,val3)
cv2.imshow("ci",ci)
show()
# ci[0,0]

### Script from George Lecakes

In [17]:
def is_outside(r, c, shape):
    if(c < 0 or c > shape[1]):
        return True
    if(r < 0 or r > shape[1]):
        return True
    else:
        return False
    
new_sample = clear_image.copy()

for r in range(clear_image.shape[0]):
    for c in range(clear_image.shape[1]):
        
        if r == clear_image.shape[0]:
            r1 = r + 1
        else:
            r1 = r - 2
        if c == clear_image.shape[1]:
            c1 = c + 1
        else:
            c1 = c - 2
        
        if(is_outside(r1, c1, clear_image.shape)):
            new_sample.itemset((r,c,0), 1)
            new_sample.itemset((r,c,1), 1)
            new_sample.itemset((r,c,2), 1)
        else:
            new_sample.itemset((r,c,0), clear_image.item((r1,c1,0)))
            new_sample.itemset((r,c,1), clear_image.item((r1,c1,1)))
            new_sample.itemset((r,c,2), clear_image.item((r1,c1,2)))

cv2.imshow("sample",new_sample)
show()

In [30]:
new_sample = clear_image.copy()

for r in range(clear_image.shape[0]):
    for c in range(clear_image.shape[1]):
        
        if r == clear_image.shape[0]:
            r1 = r + 1
        else:
            r1 = r - 2
        if c == clear_image.shape[1]:
            c1 = c + 1
        else:
            c1 = c - 2
        
        new_sample.itemset((r,c,0), clear_image.item((r1,c1,0)))
        new_sample.itemset((r,c,1), clear_image.item((r1,c1,1)))
        new_sample.itemset((r,c,2), clear_image.item((r1,c1,2)))

cv2.imshow("sample",new_sample)
show()

### Exploring Manipulation

In [64]:
height = 3
width = 3
channels = 3

clear_image = np.random.rand(height,width,channels)

In [148]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
height = int(image_file.shape[0] * scale_factor/100)
width = int(image_file.shape[1] * scale_factor/100)
dimensions = (width,height)

clear_image = cv2.resize(image_file, dimensions)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:40


In [156]:
def is_outside(r, c, shape):
    if(c < 0 or c > shape[1]):
        return True
    if(r < 0 or r > shape[1]):
        return True
    else:
        return False

In [214]:
new_sample = clear_image.copy()

for r in range(clear_image.shape[0]):
    for c in range(clear_image.shape[1]):
        
        new_sample.itemset((r,c,0), clear_image[r,c,0]*math.pi)
        new_sample.itemset((r,c,1), clear_image[r,c,0]*math.e)
        new_sample.itemset((r,c,2), clear_image[r,c,0]*math.sin(r))

cv2.imshow("sample",new_sample)
show()

In [215]:
new_sample = clear_image.copy()
diameter = 10

for r in range(clear_image.shape[0]):
    for c in range(clear_image.shape[1]):
        
        r1 = r + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
        c1 = c + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
                
        if(is_outside(r1, c1, clear_image.shape)):
            new_sample.itemset((r,c,0), 1)
            new_sample.itemset((r,c,1), 1)
            new_sample.itemset((r,c,2), 1)
        else:
            new_sample.itemset((r,c,0), clear_image[r1,c1,0])
            new_sample.itemset((r,c,1), clear_image[r1,c1,1])
            new_sample.itemset((r,c,2), clear_image[r1,c1,2])

cv2.imshow("sample",new_sample)
show()

IndexError: index 520 is out of bounds for axis 1 with size 520

In [206]:
np.random.uniform(-0.5,0.5)

-0.2081072248849436

In [122]:
r = 1
c = 2
clear_image[r,c,0]*3

0.12562991010746727

In [69]:
clear_image

array([[[0.20973378, 0.25803559, 0.25817509],
        [0.43925552, 0.2059181 , 0.03571784],
        [0.65770722, 0.8368351 , 0.90041032]],

       [[0.8875103 , 0.71830661, 0.89451212],
        [0.58531701, 0.53531046, 0.97802003],
        [0.04187664, 0.80996184, 0.63212842]],

       [[0.6930825 , 0.77708017, 0.12672578],
        [0.4199977 , 0.13197278, 0.51458575],
        [0.79286132, 0.6976383 , 0.70319765]]])

In [91]:
cv2.imshow("sample",clear_image)
show()

In [85]:
clear_image.item((0,0,2))

0.25817509219048973

In [133]:
ci = clear_image.copy()
ci[0,0,0] = clear_image[0,0,0]*math.pi
ci[0,0,1] = clear_image[0,0,1]*math.pi
ci[0,0,2] = clear_image[0,0,2]*math.pi
cv2.imshow("sample",ci)
show()

In [100]:
ci

array([[[0.62920134, 1.25840267, 1.88760401],
        [0.43925552, 0.2059181 , 0.03571784],
        [0.65770722, 0.8368351 , 0.90041032]],

       [[0.8875103 , 0.71830661, 0.89451212],
        [0.58531701, 0.53531046, 0.97802003],
        [0.04187664, 0.80996184, 0.63212842]],

       [[0.6930825 , 0.77708017, 0.12672578],
        [0.4199977 , 0.13197278, 0.51458575],
        [0.79286132, 0.6976383 , 0.70319765]]])

In [131]:
math.sin(clear_image[0,0,0])

0.20819951962077496