### Import Libraries

In [42]:
import cv2
import numpy as np
import random
import math

### Define `show()` to control termination of image window

In [43]:
def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

### Read in the image. If width is greater than 800 pixels, reduce size.

In [111]:
path = "../../media/images/"
clear_image = cv2.imread(path+"flyeye.jpg", cv2.IMREAD_UNCHANGED)

if clear_image.shape[1] > 800:
    scale_factor = 50
    height = int(clear_image.shape[0] * scale_factor/100)
    width = int(clear_image.shape[1] * scale_factor/100)
    dimensions = (width,height)

    clear_image = cv2.resize(clear_image, dimensions)

### Display image

In [ ]:
cv2.imshow("Resized Image",clear_image)

show()

### Display shape information of image (number of rows, number of columns and number of channels)

In [ ]:
clear_image.shape

### Two ways of displaying value of a pixel of particular channel

In [ ]:
clear_image[200,200,2], clear_image.item((200,200,2))

### Make copy of image to play around with.

In [ ]:
ci = clear_image.copy()
cv2.imshow("ci", ci)
show()

### Two ways of setting the value of a pixel of a particular channel

In [ ]:
ci = clear_image.copy()
ci[0,0] = (0,0,4)
ci[0,0,2], clear_image[0,0,2]

In [ ]:
ci.itemset((0,0,2), 42)
ci[0,0,2], clear_image[0,0,2]

### Display a slice of the image

In [ ]:
ci = clear_image.copy()
cv2.imshow("ci",ci[100:,100:,0])
show()

### Create data with NumPy and display

In [6]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.rand(height,width,channels)
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

In [31]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.randn(height,width,channels)
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

### Not quite getting it with randints

In [40]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

start = 1
stop = 201
number = 200
channels = 3

try:
    contrived_image = np.random.randint(start,stop,(number,number))
    cv2.imshow("ci",contrived_image)
except:
    print("Entered faulty number of channels")
show()

Entered faulty number of channels


In [36]:
contrived_image.shape

(200, 200, 3)

In [46]:
clear_image[0,0]

array([37, 43, 42], dtype=uint8)

## Modifying Images
### First, change value of colours deterministically

In [47]:
ci = clear_image.copy()
for r in range(ci.shape[0]):
    for c in range(ci.shape[1]):
#         if r > 128:
#             val = ci[r,c,0]
#         else:
        val1 = ci[c,r,0]
        val2 = ci[c,r,1]
        val3 = ci[c,r,2]
        ci[r,c] = (val3,val3,val3)
cv2.imshow("ci",ci)
show()
# ci[0,0]

In [88]:
sample = cv2.imread(path+"sample.jpg", cv2.IMREAD_UNCHANGED)
cv2.imshow("sample",sample)
show()

In [50]:
sample.shape

(20, 20, 3)

In [55]:
#get first row of sample

sample[1]

array([[ 65,  83, 146],
       [ 59,  81, 123],
       [ 60,  81, 102],
       [ 60,  79,  82],
       [ 59,  78,  63],
       [ 67,  85,  54],
       [ 68,  85,  41],
       [ 67,  86,  29],
       [ 65,  87,  29],
       [ 65,  88,  26],
       [ 69,  90,  27],
       [ 73,  89,  28],
       [ 75,  90,  29],
       [ 78,  89,  27],
       [ 82,  90,  29],
       [ 80,  88,  27],
       [ 75,  90,  28],
       [ 74,  89,  28],
       [ 73,  87,  29],
       [ 79,  90,  34]], dtype=uint8)

In [66]:
new_sample = []
for i in sample[1]:
    r = sample[0]
    new_sample.append(r)
new_sample

[array([[ 65,  84, 121],
        [ 55,  77,  95],
        [ 59,  79,  80],
        [ 63,  80,  66],
        [ 64,  83,  50],
        [ 69,  89,  44],
        [ 71,  88,  37],
        [ 68,  85,  28],
        [ 70,  87,  30],
        [ 74,  92,  33],
        [ 71,  89,  30],
        [ 71,  85,  31],
        [ 74,  86,  34],
        [ 75,  85,  32],
        [ 78,  89,  33],
        [ 78,  88,  35],
        [ 78,  90,  32],
        [ 78,  89,  33],
        [ 77,  87,  34],
        [ 79,  88,  37]], dtype=uint8),
 array([[ 65,  84, 121],
        [ 55,  77,  95],
        [ 59,  79,  80],
        [ 63,  80,  66],
        [ 64,  83,  50],
        [ 69,  89,  44],
        [ 71,  88,  37],
        [ 68,  85,  28],
        [ 70,  87,  30],
        [ 74,  92,  33],
        [ 71,  89,  30],
        [ 71,  85,  31],
        [ 74,  86,  34],
        [ 75,  85,  32],
        [ 78,  89,  33],
        [ 78,  88,  35],
        [ 78,  90,  32],
        [ 78,  89,  33],
        [ 77,  87,  34],
        [ 

In [95]:
new_sample = sample[:2,:3].copy()
new_sample

array([[[ 65,  84, 121],
        [ 55,  77,  95],
        [ 59,  79,  80]],

       [[ 65,  83, 146],
        [ 59,  81, 123],
        [ 60,  81, 102]]], dtype=uint8)

In [79]:
new_sample[0,0,0] = new_sample.item((1,1,2))
new_sample.item((0,0,0))

123

In [173]:
to_process = clear_image.copy()
new_sample = new_sample.copy()

def is_outside(r, c, shape):
    if(c < 0 or c > shape[1]):
        return True
    if(r < 0 or r > shape[1]):
        return True
    else:
        return False
    
for r in range(new_sample.shape[0]):
    for c in range(new_sample.shape[1]):
        
        if r == 400:
            r1 = r + 1
        else:
            r1 = r - 2
        if c == 400:
            c1 = c + 1
        else:
            c1 = c - 2
        
        if(is_outside(r1, c1, to_process.shape)):
            new_sample.itemset((r,c,0), 1)
            new_sample.itemset((r,c,1), 1)
            new_sample.itemset((r,c,2), 1)
        else:
            new_sample.itemset((r,c,0), to_process.item((c1,r1,0)))
            new_sample.itemset((r,c,1), to_process.item((r1,c1,1)))
            new_sample.itemset((r,c,2), to_process.item((c1,r1,2)))

cv2.imshow("sample",new_sample)
show()

IndexError: index 433 is out of bounds for axis 0 with size 433

### This is working for square images. But not for rectangular images. Why?

In [180]:
clear_image = cv2.imread(path+"flys.jpg", cv2.IMREAD_UNCHANGED)

if clear_image.shape[1] > 5800:
    scale_factor = 50
    height = int(clear_image.shape[0] * scale_factor/100)
    width = int(clear_image.shape[1] * scale_factor/100)
    dimensions = (width,height)

    clear_image = cv2.resize(clear_image, dimensions)

to_process = clear_image
new_sample = to_process.copy()

rows = new_sample.shape[0]
columns = new_sample.shape[1]

for r in range(rows):
    for c in range(columns):
        
        if r == rows:
            r1 = r + 1
        else:
            r1 = r - 1
        if c == columns:
            c1 = c + 1
        else:
            c1 = c - 1
        
        new_sample.itemset((r,c,0), to_process.item((c1,r1,0)))
        new_sample.itemset((r,c,1), to_process.item((r1,c1,1)))
        new_sample.itemset((r,c,2), to_process.item((c1,r1,2)))

cv2.imshow("sample",new_sample)
show()

In [181]:
clear_image.shape

(866, 866, 3)

In [182]:
new_sample.shape

(866, 866, 3)

In [127]:
to_process = clear_image.copy()
new_sample = new_sample.copy()
    
for r in range(new_sample.shape[0]):
    for c in range(new_sample.shape[1]):
        new_sample.itemset((r,c,0), to_process.item((r,c,2)))
        new_sample.itemset((r,c,1), to_process.item((r,c,0)))
        new_sample.itemset((r,c,2), to_process.item((r,c,1)))
new_sample

array([[[42, 37, 43],
        [38, 34, 39],
        [48, 45, 50],
        ...,
        [90, 30, 47],
        [88, 37, 50],
        [85, 41, 51]],

       [[45, 40, 46],
        [41, 38, 43],
        [41, 40, 46],
        ...,
        [97, 38, 54],
        [95, 41, 56],
        [93, 42, 55]],

       [[50, 47, 52],
        [50, 49, 55],
        [43, 42, 48],
        ...,
        [96, 37, 53],
        [96, 37, 53],
        [93, 33, 50]],

       ...,

       [[ 1,  4,  5],
        [10, 13, 14],
        [16, 19, 20],
        ...,
        [15,  9, 14],
        [14,  9, 15],
        [14,  9, 15]],

       [[ 7, 10, 11],
        [14, 17, 18],
        [20, 23, 24],
        ...,
        [15,  9, 14],
        [14,  8, 13],
        [13,  7, 12]],

       [[10, 13, 14],
        [16, 19, 20],
        [18, 21, 22],
        ...,
        [15,  9, 14],
        [13,  5, 13],
        [12,  2,  9]]], dtype=uint8)

In [104]:
new_sample.shape

(400, 400, 3)

In [137]:
cv2.imshow("sample",new_sample)
show()

In [83]:
new_sample.itemset((0,0,1), sample.item((1,1,2)))
new_sample.item((0,0,1))

123