# Image Manipulation with OpenCV and NumPy 

## Introduction

### Import Libraries

In [1]:
import cv2
import numpy as np
import math

### Define `show()` to control termination of image window

In [2]:
def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

### Define `image_resize()` to resize image

In [3]:
def image_resize(image):
    scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
    height = int(image.shape[0] * scale_factor/100)
    width = int(image.shape[1] * scale_factor/100)
    dimensions = (width,height)

    return cv2.resize(image, dimensions)

### Define `is_outside()` to test limits of image data

In [4]:
def is_outside(r, c, shape):
    if(c < 0 or c >= shape[1]):
        return True
    if(r < 0 or r >= shape[0]):
        return True
    else:
        return False

### Read in the image.

In [5]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

input_image = image_resize(image_file)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:100


### Display image

In [6]:
cv2.imshow("Image",input_image)
show()

### Display shape information of image (number of rows, number of columns and number of channels)

In [7]:
input_image.shape

(866, 1300, 3)

### Display a slice of the image
#### Full Colour

In [8]:
cv2.imshow("Image",input_image[200:400,200:400])
show()

#### One Channel Colour

In [9]:
cv2.imshow("Image",input_image[200:400,200:400,1])
show()

### Make a contrived image to play around with.

In [26]:
height = 500
width = 500
channels = 3
contrived_image = (np.random.rand(height,width,channels) * 10).round(2)

### Two ways of displaying value of a pixel of particular channel

In [36]:
contrived_image[:1, :1]

array([[[8.37, 6.41, 8.54]]])

In [28]:
contrived_image[1,2,1], contrived_image.item((1,2,1))

(8.56, 8.56)

### Two ways of setting the value of a pixel of a particular channel

In [29]:
image_copy = contrived_image.copy()
image_copy[0,0,2] = 42
contrived_image.item((0,0,2)), image_copy.item((0,0,2))

(8.54, 42.0)

In [37]:
image_copy[:1, :1]

array([[[ 8.37,  6.41, 42.  ]]])

In [32]:
image_copy = contrived_image.copy()
image_copy.itemset((0,0,2), 42)
contrived_image.item((0,0,2)), image_copy.item((0,0,2))

(8.54, 42.0)

In [38]:
image_copy[:1, :1]

array([[[ 8.37,  6.41, 42.  ]]])

### Create data with NumPy and display

#### Use uniformly distributed data

In [17]:
contrived_image = np.random.rand(height,width,channels)
cv2.imshow("Image",contrived_image)
show()

#### Use normally distributed data

In [18]:
contrived_image = np.random.randn(height,width,channels)
cv2.imshow("Image",contrived_image)
show()

## Modifying Images
### First, change value of colours deterministically

In [116]:
resized_image = image_resize(input_image)

Enter the scale factor by which to reduce the image size:50


In [20]:
output_image = resized_image.copy()
for r in range(output_image.shape[0]):
    for c in range(output_image.shape[1]):
        
        if(is_outside(r, c, resized_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            val_0 = output_image.item((r,c,2))
            val_1 = output_image.item((r,c,0))
            val_2 = output_image.item((r,c,1))
        output_image[r,c] = (val_2,val_0,val_1)
cv2.imshow("Image",output_image)
show()

In [39]:
output_image = resized_image.copy()
diameter = 20

for r in range(resized_image.shape[0]):
    for c in range(resized_image.shape[1]):
        
        if resized_image.item((r,c,1)) >= 128:
            r1 = 128
        else:
            r1 = math.ceil(r / 20)
        if resized_image.item((r,c,1)) >= 128:
            c1 = 128
        else:
            c1 = math.ceil(c / 20)
                
        if(is_outside(r1, c1, resized_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), resized_image.item((r1,c1,0)))
            output_image.itemset((r,c,1), resized_image.item((r1,c1,1)))
            output_image.itemset((r,c,2), resized_image.item((r1,c1,2)))
cv2.imshow("Image",output_image)
show()

In [132]:
for r in range(resized_image.shape[0]):
    for c in range(resized_image.shape[1]):
        if(is_outside(r, c, resized_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), np.min([resized_image.item((r,c,1)), resized_image.item((r,c,2))]))
            output_image.itemset((r,c,1), np.min([resized_image.item((r,c,0)), resized_image.item((r,c,2))]))
            output_image.itemset((r,c,2), np.min([resized_image.item((r,c,0)), resized_image.item((r,c,1))]))
cv2.imshow("Image",output_image)
show()

Enter the scale factor by which to reduce the image size:50


### Change pixel values using mathematical functions

In [21]:
output_image = resized_image.copy()

for r in range(resized_image.shape[0]):
    for c in range(resized_image.shape[1]):
        output_image.itemset((r,c,0), resized_image.item((r,c,0))*math.e)
        output_image.itemset((r,c,1), resized_image.item((r,c,1))*math.e)
        output_image.itemset((r,c,2), resized_image.item((r,c,2))*math.e)

cv2.imshow("Image",output_image)
show()

### Random Effects

### Script from George Lecakes demonstrating splatting
#### Using Uniformly Distributed Random Data

In [124]:
output_image = resized_image.copy()
diameter = 20

for r in range(resized_image.shape[0]):
    for c in range(resized_image.shape[1]):
        
        r1 = r + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
        c1 = c + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
                
        if(is_outside(r1, c1, resized_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), resized_image.item((r1,c1,0)))
            output_image.itemset((r,c,1), resized_image.item((r1,c1,1)))
            output_image.itemset((r,c,2), resized_image.item((r1,c1,2)))
cv2.imshow("Image",output_image)
show()

#### Using Normally Distributed Random Data

In [125]:
output_image = resized_image.copy()
diameter = 60

for r in range(resized_image.shape[0]):
    for c in range(resized_image.shape[1]):
        
        r1 = r + math.ceil(np.random.normal(-0.5,0.5) * diameter)
        c1 = c + math.ceil(np.random.normal(-0.5,0.5) * diameter)
                
        if(is_outside(r1, c1, resized_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), resized_image.item((r1,c1,0)))
            output_image.itemset((r,c,1), resized_image.item((r1,c1,1)))
            output_image.itemset((r,c,2), resized_image.item((r1,c1,2)))
cv2.imshow("Image",output_image)
show()