### Import Libraries

In [1]:
import cv2
import numpy as np
import math

### Define `show()` to control termination of image window

In [2]:
def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

### Define `image_resize()` to resize image

In [22]:
def image_resize(image):
    scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
    height = int(image.shape[0] * scale_factor/100)
    width = int(image.shape[1] * scale_factor/100)
    dimensions = (width,height)

    return cv2.resize(image, dimensions)

### Read in the image.

In [25]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

input_image = image_resize(image_file)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:100


### Display image

In [4]:
cv2.imshow("Image",input_image)
show()

### Display shape information of image (number of rows, number of columns and number of channels)

In [5]:
input_image.shape

(866, 1300, 3)

### Display a slice of the image
#### Full Colour

In [7]:
cv2.imshow("Image",input_image[200:400,200:400])
show()

#### One Channel Colour

In [8]:
cv2.imshow("Image",input_image[200:400,200:400,1])
show()

### Make a contrived image to play around with.

In [116]:
height = 100
width = 100
channels = 3
contrived_image = (np.random.rand(height,width,channels) * 10).astype(int)

### Two ways of displaying value of a pixel of particular channel

In [117]:
contrived_image[:2, :3]

array([[[7, 2, 5],
        [9, 7, 8],
        [7, 0, 3]],

       [[3, 4, 1],
        [4, 1, 7],
        [4, 7, 7]]])

In [118]:
contrived_image[1,2,1], contrived_image.item((1,2,1))

(7, 7)

### Two ways of setting the value of a pixel of a particular channel

In [123]:
image_copy = contrived_image.copy()
image_copy[0,0,2] = 41
contrived_image.item((0,0,2)), image_copy.item((0,0,2))

(5, 41)

In [124]:
image_copy[:2, :3]

array([[[ 7,  2, 41],
        [ 9,  7,  8],
        [ 7,  0,  3]],

       [[ 3,  4,  1],
        [ 4,  1,  7],
        [ 4,  7,  7]]])

In [125]:
image_copy = contrived_image.copy()
image_copy.itemset((0,0,2), 42)
contrived_image.item((0,0,2)), image_copy.item((0,0,2))

(5, 42)

In [126]:
image_copy[:2, :3]

array([[[ 7,  2, 42],
        [ 9,  7,  8],
        [ 7,  0,  3]],

       [[ 3,  4,  1],
        [ 4,  1,  7],
        [ 4,  7,  7]]])

### Create data with NumPy and display

#### Use uniformly distributed data

In [12]:
contrived_image = np.random.rand(height,width,channels)
cv2.imshow("Image",contrived_image)
show()

#### Use normally distributed data

In [13]:
contrived_image = np.random.randn(height,width,channels)
cv2.imshow("Image",contrived_image)
show()

## Modifying Images
### First, change value of colours deterministically

In [27]:
image_copy = image_resize(input_image)
for r in range(image_copy.shape[0]):
    for c in range(image_copy.shape[1]):
        
        if(is_outside(r1, c1, input_image.shape)):
            image_copy.itemset((r,c,0), 0)
            image_copy.itemset((r,c,1), 0)
            image_copy.itemset((r,c,2), 0)
        else:
            val1 = image_copy[r,c,2]
            val2 = image_copy[r,c,0]
            val3 = image_copy[r,c,1]
        image_copy[r,c] = (val3,val3,val3)
cv2.imshow("Image",image_copy)
show()

Enter the scale factor by which to reduce the image size:50


### Random Effects

In [15]:
output_image = input_image.copy()

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        output_image.itemset((r,c,0), input_image.item((r,c,0))*math.pi)
        output_image.itemset((r,c,1), input_image.item((r,c,1))*math.e)
        output_image.itemset((r,c,2), input_image.item((r,c,2))*math.sin(r))

cv2.imshow("Image",output_image)
show()

### Script from George Lecakes

In [16]:
def is_outside(r, c, shape):
    if(c < 0 or c >= shape[1]):
        return True
    if(r < 0 or r >= shape[0]):
        return True
    else:
        return False
    
output_image = input_image.copy()
diameter = 50

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        r1 = r + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
        c1 = c + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
                
        if(is_outside(r1, c1, input_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), input_image.item((r1,c1,0)))
            output_image.itemset((r,c,1), input_image.item((r1,c1,1)))
            output_image.itemset((r,c,2), input_image.item((r1,c1,2)))
cv2.imshow("Image",output_image)
show()