### Import Libraries

In [1]:
import cv2
import numpy as np
import random
import math

### Define `show()` to control termination of image window

In [2]:
def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

### Read in the image. If width is greater than 800 pixels, reduce size.

In [3]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
height = int(image_file.shape[0] * scale_factor/100)
width = int(image_file.shape[1] * scale_factor/100)
dimensions = (width,height)

input_image = cv2.resize(image_file, dimensions)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:100


### Display image

In [4]:
cv2.imshow("Image",input_image)

show()

### Display shape information of image (number of rows, number of columns and number of channels)

In [5]:
input_image.shape

(866, 1300, 3)

### Two ways of displaying value of a pixel of particular channel

In [6]:
input_image[200,200,2], input_image.item((200,200,2))

(19, 19)

### Make copy of image to play around with.

In [7]:
image_copy = input_image.copy()
cv2.imshow("Image", image_copy)
show()

### Two ways of setting the value of a pixel of a particular channel

In [8]:
image_copy = input_image.copy()
image_copy[0,0] = (0,0,4)
image_copy[0,0,2], input_image[0,0,2]

(4, 136)

In [9]:
image_copy.itemset((0,0,2), 42)
image_copy[0,0,2], input_image[0,0,2]

(42, 136)

### Display a slice of the image

In [10]:
image_copy = input_image.copy()
cv2.imshow("Image",image_copy[100:,100:,0])
show()

### Create data with NumPy and display

In [11]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.rand(height,width,channels)
    cv2.imshow("Image",contrived_image)
except:
    print("Entered faulty number of channels")
show()

In [12]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

height = 200
width = 200
channels = 3

try:
    contrived_image = np.random.randn(height,width,channels)
    cv2.imshow("Image",contrived_image)
except:
    print("Entered faulty number of channels")
show()

### Not quite getting it with randints

In [13]:
import cv2
import numpy as np

def show():
    while True:
        if(cv2.waitKey(1) & 0xFF == ord("q")):
            break
    cv2.destroyAllWindows()

start = 1
stop = 201
number = 200
channels = 3

try:
    contrived_image = np.random.randint(start,stop,(number,number))
    cv2.imshow("Image",contrived_image)
except:
    print("Entered faulty number of channels")
show()

Entered faulty number of channels


In [14]:
contrived_image.shape

(200, 200)

In [15]:
input_image[0,0]

array([109, 122, 136], dtype=uint8)

## Modifying Images
### First, change value of colours deterministically

In [16]:
image_copy = input_image.copy()
for r in range(image_copy.shape[0]):
    for c in range(image_copy.shape[1]):
#         if r > 128:
#             val = image_copy[r,c,0]
#         else:
        val1 = image_copy[r,c,2]
        val2 = image_copy[r,c,0]
        val3 = image_copy[r,c,1]
        image_copy[r,c] = (val3,val3,val3)
cv2.imshow("Image",image_copy)
show()
# image_copy[0,0]

### Script from George Lecakes

In [56]:
def is_outside(r, c, shape):
    if(c < 0 or c >= shape[1]):
        return True
    if(r < 0 or r >= shape[0]):
        return True
    else:
        return False
    
output_image = input_image.copy()

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        if r == input_image.shape[0]:
            r1 = r + 1
        else:
            r1 = r - 2
        if c == input_image.shape[1]:
            c1 = c + 1
        else:
            c1 = c - 2
        
        if(is_outside(r1, c1, input_image.shape)):
            output_image.itemset((r,c,0), 1)
            output_image.itemset((r,c,1), 1)
            output_image.itemset((r,c,2), 1)
        else:
            output_image.itemset((r,c,0), input_image.item((r1,c1,0)))
            output_image.itemset((r,c,1), input_image.item((r1,c1,1)))
            output_image.itemset((r,c,2), input_image.item((r1,c1,2)))

cv2.imshow("Image",output_image)
show()

In [18]:
output_image = input_image.copy()

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        if r == input_image.shape[0]:
            r1 = r + 1
        else:
            r1 = r - 2
        if c == input_image.shape[1]:
            c1 = c + 1
        else:
            c1 = c - 2
        
        output_image.itemset((r,c,0), input_image.item((r1,c1,0)))
        output_image.itemset((r,c,1), input_image.item((r1,c1,1)))
        output_image.itemset((r,c,2), input_image.item((r1,c1,2)))

cv2.imshow("Image",output_image)
show()

### Exploring Manipulation

In [45]:
height = 2
width = 3
channels = 3

input_image = np.random.rand(height,width,channels)

In [59]:
path = "../../media/images/"
file_name = input("Enter file name to use:")
image_file = cv2.imread(path+file_name, cv2.IMREAD_UNCHANGED)

scale_factor = int(input("Enter the scale factor by which to reduce the image size:"))
height = int(image_file.shape[0] * scale_factor/100)
width = int(image_file.shape[1] * scale_factor/100)
dimensions = (width,height)

input_image = cv2.resize(image_file, dimensions)

Enter file name to use:fly.jpg
Enter the scale factor by which to reduce the image size:25


In [54]:
def is_outside(r, c, shape):
    if(c < 0 or c >= shape[1]):
        return True
    if(r < 0 or r >= shape[0]):
        return True
    else:
        return False

In [22]:
output_image = input_image.copy()

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        output_image.itemset((r,c,0), input_image[r,c,0]*math.pi)
        output_image.itemset((r,c,1), input_image[r,c,0]*math.e)
        output_image.itemset((r,c,2), input_image[r,c,0]*math.sin(r))

cv2.imshow("Image",output_image)
show()

In [62]:
output_image = input_image.copy()
diameter = 50

for r in range(input_image.shape[0]):
    for c in range(input_image.shape[1]):
        
        r1 = r + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
        c1 = c + math.ceil(np.random.uniform(-0.5,0.5) * diameter)
                
        if(is_outside(r1, c1, input_image.shape)):
            output_image.itemset((r,c,0), 0)
            output_image.itemset((r,c,1), 0)
            output_image.itemset((r,c,2), 0)
        else:
            output_image.itemset((r,c,0), input_image[r1,c1,0])
            output_image.itemset((r,c,1), input_image[r1,c1,1])
            output_image.itemset((r,c,2), input_image[r1,c1,2])

cv2.imshow("Image",output_image)
show()

In [25]:
r = 1
c = 2
input_image[r,c,0]*3

315

In [26]:
input_image

array([[[109, 122, 136],
        [107, 123, 136],
        [104, 118, 136],
        ...,
        [ 59,  54,  55],
        [ 53,  55,  55],
        [ 55,  55,  55]],

       [[110, 123, 137],
        [107, 120, 134],
        [105, 121, 134],
        ...,
        [ 60,  59,  61],
        [ 53,  55,  55],
        [ 57,  57,  57]],

       [[105, 118, 132],
        [106, 119, 133],
        [103, 116, 130],
        ...,
        [ 61,  60,  62],
        [ 52,  57,  56],
        [ 59,  59,  59]],

       ...,

       [[ 89,  89, 101],
        [ 82,  84,  95],
        [ 89,  91, 102],
        ...,
        [106, 113, 138],
        [101, 108, 133],
        [108, 113, 138]],

       [[ 81,  83,  94],
        [ 84,  82, 101],
        [ 88,  85, 101],
        ...,
        [112, 119, 144],
        [111, 119, 142],
        [106, 115, 135]],

       [[ 82,  82,  98],
        [ 88,  88, 104],
        [ 93,  94, 108],
        ...,
        [124, 131, 156],
        [115, 123, 146],
        [103, 112, 132]]

In [27]:
cv2.imshow("Image",input_image)
show()

In [28]:
input_image.item((0,0,2))

136

In [29]:
image_copy = input_image.copy()
image_copy[0,0,0] = input_image[0,0,0]*math.pi
image_copy[0,0,1] = input_image[0,0,1]*math.pi
image_copy[0,0,2] = input_image[0,0,2]*math.pi
cv2.imshow("Image",image_copy)
show()

In [30]:
image_copy

array([[[ 86, 127, 171],
        [107, 123, 136],
        [104, 118, 136],
        ...,
        [ 59,  54,  55],
        [ 53,  55,  55],
        [ 55,  55,  55]],

       [[110, 123, 137],
        [107, 120, 134],
        [105, 121, 134],
        ...,
        [ 60,  59,  61],
        [ 53,  55,  55],
        [ 57,  57,  57]],

       [[105, 118, 132],
        [106, 119, 133],
        [103, 116, 130],
        ...,
        [ 61,  60,  62],
        [ 52,  57,  56],
        [ 59,  59,  59]],

       ...,

       [[ 89,  89, 101],
        [ 82,  84,  95],
        [ 89,  91, 102],
        ...,
        [106, 113, 138],
        [101, 108, 133],
        [108, 113, 138]],

       [[ 81,  83,  94],
        [ 84,  82, 101],
        [ 88,  85, 101],
        ...,
        [112, 119, 144],
        [111, 119, 142],
        [106, 115, 135]],

       [[ 82,  82,  98],
        [ 88,  88, 104],
        [ 93,  94, 108],
        ...,
        [124, 131, 156],
        [115, 123, 146],
        [103, 112, 132]]

In [31]:
math.sin(input_image[0,0,0])

0.8167426066363169